[server]
#host-name=
#domain-name=local
use-ipv4=yes
use-ipv6=no
check-response-ttl=no
use-iff-running=no
enable-dbus=yes
disallow-other-stacks=no
# 不限制网卡（NAS 是 enp4s0、N1 是 eth0，写死网卡名会导致 AirPrint 广播不出去）

[publish]
publish-hinfo=no
publish-workstation=no
publish-aaaa-on-ipv4=no
publish-a-on-ipv6=no

[reflector]
enable-reflector=no
reflect-ipv=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-as=65536
rlimit-nproc=3
